### ISSUE TITLE
--include-namespaces=kube-system does not overwrite the default exclusion

### ISSUE THREAD

**Issue by CookieComputing** [hjacobs/kube-janitor#13]
If I run `--include-namespaces=kube-system` without explicitly changes `--exclude-namespaces`, `kube-janitor` does not overwrite the exclusion. Is this by design, or should this be a change?

**Comment by hjacobs** [comment]
This is by design, I think "excludes" should have precedence (for safety reasons) --- you basically limit the namespaces by specifying `--include-namespaces` as the default is "all" (same as `--include-namespaces=all`). I would recommend that you _only_ change `--exclude-namespaces` if you want to include `kube-system` (and all other namespaces).

**Comment by hjacobs** [comment]
I think we should make this behaviour more clear in the README, see #16
